# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='conference',
            field=models.ManyToManyField(through='confreg.Registrant', to='confreg.Conference'),
        ),
    ]
