# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0003_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationRoomOccupant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Accommodation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Person')),
            ],
        ),
    ]
