# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0004_accommodationroomoccupant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationroomoccupant',
            name='person',
        ),
        migrations.AddField(
            model_name='accommodationroomoccupant',
            name='registrant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confreg.Registrant'),
            preserve_default=False,
        ),
    ]
