# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0005_auto_20170110_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='accommodation',
            field=models.ManyToManyField(through='confreg.AccommodationRoomOccupant', to='confreg.Accommodation'),
        ),
    ]
