# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0008_personmanagedbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ManyToManyField(through='confreg.PersonManagedByUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
